### ISSUE TITLE
Chef 13

### ISSUE THREAD

**Issue by kylegoch** [vkhatri/chef-filebeat#102]
Any reason the Chef Version was locked to Chef 12? I had been using it just fine in Chef 13 until cookbook version 0.4.9. But now the Chef Version lock in 0.5.0 makes it unusable in Chef 13.

I have pinned to 0.4.9 as a workaround.

**Comment by vkhatri** [comment]
@kylegoch I thought I updated the issue, but looks like I did not.

It was a typo and fixed. Will be releasing a new cookbook version soon.
