### ISSUE TITLE
prospectors config files accumulates

### ISSUE THREAD

**Issue by hyksos** [vkhatri/chef-filebeat#103]
Hi Virender,

Thanks for the filebeat cookbook!

I assume you are using this cookbook, and I was wondering how you currently deal with its inability to maintain the prospector config files in sync.

We tried using the filebeat_prospector lwrp and it seems to be working fine but when such a prospector is no longer defined in our configuration, Chef leave the prospector config file in node['filebeat']['prospectors_dir'].
Maybe this would also happen on name change and app1 prospector would also be left behind?
`filebeat_prospector 'app1' do`
to
`filebeat_prospector 'app2' do`

So without being silly :) You never change your mind or wish to remove prospectors you have configured?
How do you deal with this yourself, we have forked the cookbook so we can look at how we can fix that but I was curious how you dealt with it in your own deployment?

I saw the issue about prospector clean up when defined with node attributes, this is essentially the same issue but it seems to have received no love, which means people using this cookbook found a workaround or fixed this issue on their side for sure. If not how can filebeat be configured correctly if it keeps all the old prospectors I have unconfigured?

Martin

**Comment by hyksos** [comment]
Hi again,

I think for the lwrp the solution was simpler than I though, I checked best practices for providers and clean up and chef_filebeat already support this best practice.

[Chef style guide](https://github.com/pulseenergy/chef-style-guide#providers)

To remove(cleanly) a prospector created via the prospector lwrp you just need to keep it in your configuration and call the :delete action on it:
```
filebeat_prospector 'filebeat' do
  action :delete
end
```
With or without it's full config included, as long as the action is :delete the prospector will be cleaned from the disk and filebeat restarted.
This would also be how you do rename, mark the old with :delete and create a new resource with the new name.
As mentioned in the best practices, you need to leave this "tombstone resource" in your config at least until all nodes that needs to clean the files have converged.

Maybe I'm missing something, not a chef guru here, but this appear to work AND be a best practice around lwrp.

Martin

**Comment by vkhatri** [comment]
Cleaning up resources with lwrp `:delete` action is the only option currently supported by the cookbook.

However, like you mentioned there are other ways to clean up the resources discussed in the PR and not worry about the cleanup.

Next release `v0.5.1` will have those options, I will try to release it over the weekend.

**Comment by vkhatri** [comment]
Fixed in master. Closing. Next release `v1.0.0` will have this fix.
