### ISSUE TITLE
Error executing action `start` on resource 'service[filebeat]'

### ISSUE THREAD

**Issue by sagar1730** [vkhatri/chef-filebeat#11]
Hi vkhatri,

I am getting the following error while I tried to test this cookbook on Vagrant with Chef-solo. I am using 'bento/ubuntu-14.04' box on Vagrant.

Error executing action `start` on resource 'service[filebeat]'

Even it fails to restart. So far I didn't mess with the file /etc/filebeat/filebeat.yml. I am new to this, I would glad if you assist me on this.

**Comment by vkhatri** [comment]
@sagar1730 Could you share you `kitchen` configuration?  

You might be missing [prospectors](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html) configuration. You can checkout an example [here](https://github.com/vkhatri/chef-filebeat#how-to-add-filebeat-prospectors-via-node-attribute).

You also need to configure an [output](https://www.elastic.co/guide/en/beats/libbeat/1.0.0-rc2/configuration.html#configuration-output).

You can try to start the service manually to see the exact error.

I am planning to work on adding `kitchen` test this week.

**Comment by sagar1730** [comment]
Oh Thanks a lot Virender. I have added path in prospector section and now its working honey-smooth in Vagrant. I hope it will work flawless on AWS as well with these settings.

**Comment by SaravananPerumal23** [comment]
Hi am facing issue when i use runit to start filebeat. After setting the node "default['filebeat']['service']['init_style'] = 'runit'", i get the error when use this cookbook at first

# 

```
       Error executing action `restart` on resource 'service[filebeat]'
       ================================================================================

       Mixlib::ShellOut::ShellCommandFailed
       ------------------------------------
       Expected process to exit with [0], but received '1'
       ---- Begin output of /sbin/sv restart /etc/service/filebeat ----
       STDOUT: timeout: down: /etc/service/filebeat: 1s, normally up, want up
       STDERR: 
       ---- End output of /sbin/sv restart /etc/service/filebeat ----
       Ran /sbin/sv restart /etc/service/filebeat returned 1
```

But when i do the Kitchen converge the next time, it works fine.. Need some troubleshooting steps
