### ISSUE TITLE
v1.3.0 tag missing

### ISSUE THREAD

**Issue by tommylogik** [vkhatri/chef-filebeat#124]
https://supermarket.chef.io/cookbooks/filebeat refers to cookbook tag v1.3.0 as well as the tag for https://github.com/vkhatri/chef-filebeat/commit/d1aac91f20e8af02fd43486b1e5f91c38eaf654c
refers to v1.3.0.

**Comment by vkhatri** [comment]
@tommylogik Thank you for reporting.

Released tag v1.3.0.

**Comment by tommylogik** [comment]
YW! Thanks for the quick response @vkhatri
