### ISSUE TITLE
filebeat recipe fails on Windows

### ISSUE THREAD

**Issue by aprice** [vkhatri/chef-filebeat#126]
Converging the filebeat::default recipe (CB version 1.4.0) on Windows using the defaults (just to install Filebeat) gives an error:

```
Error executing action `create` on resource 'directory[/var/log/filebeat]'
```

It appears that the default log directory is not OS-aware, it always defaults to /var/log/filebeat', which obviously won't exist on Windows. Overriding `node['filebeat']['log_dir']` is of course a workaround, but it should probably work out-of-the-box since Windows support is advertised.

**Comment by vkhatri** [comment]
@aprice Sorry for the long delay in response.

Fixed by `v2.0.0+`
