### ISSUE TITLE
Prospector and filebeat configs leaking sensitive data

### ISSUE THREAD

**Issue by kovyrin** [vkhatri/chef-filebeat#129]
Hello,

We are using the cookbook for deploying filebeat in a secure environment and it means both filebeat.yml (x-pack monitoring configs) and prospector configs contain ES secrets. I've noticed, that those configs are not marked as sensitive and chef client leaks secrets into its logs as diffs.

I've raised #127 and #128 to fix the issue.

Let me know if you have any questions.

**Comment by vkhatri** [comment]
@kovyrin  Sorry for the delay. PRs merged. 

Thank you for your contribution!

👍
