### ISSUE TITLE
which version of chef-filebeat is supported/tested for chef11

### ISSUE THREAD

**Issue by SandeepMajety** [vkhatri/chef-filebeat#130]
which version of chef-filebeat is supported/tested for chef11.
So wanted to know which version of filebeat supports chef11. Thanks in advance!

The latest filebeat version is not supported by chef11. I am getting issues as
E, [2017-09-03T16:57:29.094321 #16978] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2017-09-03T16:57:29.094360 #16978] ERROR -- Kitchen: Message: Kitchen YAML file /Users/vkhatri/content/git/filebeat/libraries/.kitchen.yml does not exist.

Relevant File Content:
----------------------
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:

172:          raise
173:        end
174:
175:        def load_libraries_from_cookbook(cookbook_name)
176:          files_in_cookbook_by_segment(cookbook_name, :libraries).each do |filename|
177:            begin
178:              Chef::Log.debug("Loading cookbook #{cookbook_name}'s library file: #{filename}")
179>>             Kernel.load(filename)
180:              @events.library_file_loaded(filename)
181:            rescue Exception => e
182:              @events.library_file_load_failed(filename, e)
183:              raise
184:            end
185:          end
186:        end
187:
188:        def load_lwrps_from_cookbook(cookbook_name)

**Comment by devsibwarra** [comment]
Checking the [changelog](https://github.com/vkhatri/chef-filebeat/blob/master/CHANGELOG.md), it has the following comment for v1.0.0, so the version prior to that _might_ work
> Virender Khatri - Dropped support for Chef <12.x

**Comment by vkhatri** [comment]
You can try the release `v0.5.0`.

https://supermarket.chef.io/cookbooks/filebeat/versions/0.5.0

Closing.
