### ISSUE TITLE
windows service deleted and added when no updates

### ISSUE THREAD

**Issue by brianbaker** [vkhatri/chef-filebeat#134]
The [powershell script](https://github.com/vkhatri/chef-filebeat/blob/master/recipes/service.rb#L21) that installs the windows service gets executed every time chef client runs even though there are no config or version upgrades to process.  Is there any way to prevent this or should this happen upstream in the powershell provided by elastic?

**Comment by vkhatri** [comment]
Will take a look.

**Comment by vkhatri** [comment]
@brianbaker  I think defining `powershell_script` attribute `creates` or `not_if` should fix the issue.

**Comment by vkhatri** [comment]
Fixed in `v2.4.0`.
