### ISSUE TITLE
how do i add this file?

### ISSUE THREAD

**Issue by staticfrost** [vkhatri/chef-filebeat#136]
I have this in my filebeat.yml

How do I do that with this cookbook?

filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.*

**Comment by mburns** [comment]
You can look at one of the examples and remove the lines that don't make sense or match your desired config. `type`, `enabled`, and `paths` are pretty straightforward.

https://github.com/vkhatri/chef-filebeat/blob/38ed02462f47c5c1210dbc7201921ed7b1e32194/test/cookbooks/filebeat_test/recipes/default.rb

Then test to confirm :)

**Comment by vkhatri** [comment]
Closing. Please reopen if need to.
