### ISSUE TITLE
No such cookbook: elastic_repo 

### ISSUE THREAD

**Issue by suwblk** [vkhatri/chef-filebeat#146]
Hi, I am trying to run your filebeat cookbook.  After adding the source dependencies "berks install" downloaded the dependency cookbooks.

In berksfile added as cookbook 'elastic_repo', '~> 1.1.1', git: 'https://github.com/vkhatri/chef-elastic-repo.git'

It got downloaded in to a folder named "chef-elastic-repo". But chef-client  --local-mode  --override-runlist   filebeat command fails with below error.

```bash
Missing Cookbooks:
------------------
No such cookbook: elastic_repo

Expanded Run List:
------------------
* filebeat

System Info:
------------
chef_version=13.8.5
platform=windows
platform_version=10.0.14393
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
program_name=*****../../bin/chef-client
executable=*****chef-client

Can you please suggest a solution for this soon ?
```

**Comment by vkhatri** [comment]
@suwblk I am able to run kitchen test without any issue or adding `elastic_repo` source in Berksfile.

Are you still facing this issue?
