### ISSUE TITLE
Correct format for using modules

### ISSUE THREAD

**Issue by geoff-carr-bzy** [vkhatri/chef-filebeat#154]
Firstly thank you for a great cookbook!

Perhaps I am trying to use modules incorrectly, but is seems with Filebeat 6.x each mode requires `- module:` before the module name in the `filebeat.yml` configuration. If I add the module name as a string to the attribute then I just end up with `- apache2` which does not work. I have tried to use a hash for the attribute like: -
```
c['filebeat.modules'] = { 'module' => 'apache2' }
```
but then end up with: -
```
filebeat.modules:
  module: apache2
```
which again does not work as is missing the `-` before `module:`.

I guess I could add `module: apache2` as a string to the attribute but just wondered if that was the best way? Also, it is necessary for me to add additional configuration to the module as per the follwong example: -
```
filebeat.modules:
- module: apache2
  access:
    enabled: true
    var.paths: ["/etc/httpd/logs/access_log*"]
    input:
      fields:
        System: Apache
```
Is there a way that this additional "[Advanced Settings](https://www.elastic.co/guide/en/beats/filebeat/current/advanced-settings.html)" can be added in the attributes?

**Comment by vkhatri** [comment]
@IcedGoblin Module configuration should be a List Item. e.g.

```ruby
c['filebeat.modules'] = [{ 'module' => 'apache2' }]
```

Module coniguration is [optional](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-modules.html).
