### ISSUE TITLE
Plans for LWRP / Custom Resources

### ISSUE THREAD

**Issue by spuder** [vkhatri/chef-filebeat#18]
Great cookbook. Because the configuration is done through node attributes, this has the potential to create really big role/policy files. Think if you want to manage 20 different files, the json on the node/role attributes would become very large. 

Are there any plans to add LWRP or custom resources so that users could create wrapper cookbooks? 

The [elasticsearch](https://github.com/elastic/cookbook-elasticsearch) and [logstash](https://github.com/lusis/chef-logstash) cookbooks are great examples of HWRP and LWRP cookbooks. 

Here is the [documentation for custom resources](https://docs.chef.io/custom_resources.html) which replace LWRP and HWRP however they only work with chef 12.5 or newer

**Comment by vkhatri** [comment]
Hello! Thank you for raising this issue, I have been thinking about adding
LWRP from sometime. I will take a look on reference cookbooks.

I am currently traveling and will be able to add LWRP support next week.
Let me know if you have something going on.

**Comment by vkhatri** [comment]
Published v0.2.6 with LWRP resource.

**Comment by vkhatri** [comment]
Closing, LWRP added.
