### ISSUE TITLE
TLS configuration for logstash output?

### ISSUE THREAD

**Issue by cbmccoy** [vkhatri/chef-filebeat#19]
What would be the best way to add TLS authentication to the logstash output config section?

**Comment by vkhatri** [comment]
Hello! Sorry for the delayed response.

I am planning to publish new cookbook version with enough examples to cover
different scenarios including LWRP, next week.

You can add logstash tls output configuration via attribute
node['filebeat']['config']['output']['logstash']['tls']['certificate..'] =
value.

You can find configuration here -
https://github.com/elastic/libbeat/blob/master/etc/libbeat.yml

Let me know if this works for you.

**Comment by runningman84** [comment]
lwrp sounds really great. Right now it is a pain to configure it like this

```
a = {
  'paths' => ["/var/log/sensu/*"],
  'type' => "log",
  'fields' => {
    'type' => "sensu"
  },
  'fields_under_root' => true
}

default['filebeat']['prospectors']['sensu']['filebeat']['prospectors'] = [a]

a = {
  'paths' => ["/var/log/chef/*"],
  'type' => "log",
  'fields' => {
    'type' => "chef"
  },
  'fields_under_root' => true
}

default['filebeat']['prospectors']['chef']['filebeat']['prospectors'] = [a]
```

**Comment by vkhatri** [comment]
Published v0.2.6 with LWRP resource.

**Comment by vkhatri** [comment]
I think it would be handy to have LWRP for output configuration too.

**Comment by pmoosh** [comment]
So how do you enable SSL for the logstash output?

Ok I got that done :-) 
something like: 
default['filebeat']['config']['output']['logstash']['tls']['insecure'] = true

works.

**Comment by vkhatri** [comment]
Here is the updated doc reference for logstash tls config - https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-tls.html

Also, updated cookbook examples.
