### ISSUE TITLE
Question - How do you automate uploading the template?

### ISSUE THREAD

**Issue by spuder** [vkhatri/chef-filebeat#24]
The filebeat documentation instructs the user to upload an index template to elasticsearch

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html#filebeat-template

```
curl -XPUT 'http://localhost:9200/_template/filebeat?pretty' -d@/etc/filebeat/filebeat.template.json
```

It doesn't appear that the cookbook supports doing that automatically. Is this a manual step? 

I'm deploying elasticsearch into production behind a firewall where I don't have direct access to upload a template manually. 

Maybe the cookbook could automate this with http_request. 
https://docs.chef.io/resource_http_request.html

**Comment by vkhatri** [comment]
@spuder Sorry for the delayed response. I think we can add another resource `filebeat_mapping` to manage ES template.

**Comment by nukepuppy** [comment]
I'm trying to evaluate using this cookbook or not.. because the install is so simple.. and the complications I'm seeing and things it doesn't support yet..

this sounds like something you would need.. no matter what?

**Comment by muhh** [comment]
Reading https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-template.html#filebeat-template because I need this now myself, I'd say that filebeat will do the upload itself. 
The cookbook just needs to create the template file in the default location.

Right?

**Comment by vkhatri** [comment]
I think so. Adding an optional cookbook file resource for the template will do the trick.

Filebeat cookbook:

```ruby
default['filebeat']['source_template'] = false
default['filebeat']['source_template_cookbook'] = nil
default['filebeat']['source_template'_cookbok_file] = nil
```

```ruby
if node['filebeat']['source_template']
  cookbook_file '/etc/filebeat/template.json....' do
    cookbook node['filebeat']['source_template_cookbook']
    source node['filebeat']['source_template_cookbook_file']
  end
end
```

Wrapper cookbook:

```
default['filebeat']['source_template_cookbook'] = 'filebeat-wrapper'
default['filebeat']['source_template'_cookbok_file] = 'filebeat-template.json'
```

**Comment by vkhatri** [comment]
On the second note, IMHO, it is better off part of the wrapper cookbook. I do not see any value adding the resource to the filebeat cookbook, as it is an optional resource and the template file is not part of the filebeat cookbook.
