### ISSUE TITLE
filebeat on windows

### ISSUE THREAD

**Issue by pmoosh** [vkhatri/chef-filebeat#27]
When I look at the filebeat service via "Services" I see it starting with -c pointing to the the installation dir.
However the config file will be copied to /etc/filebeat just like on Linux. So where should it be?

**Comment by vkhatri** [comment]
@pmoosh Sorry to say this, but i do not have any windows environment to test it out. It might take me some time to look into it.

**Comment by pmoosh** [comment]
@vkhatri  I use the following test kitchen config:
- name: windows-2012r2
  transport:
    name: winrm
  driver_config:
    box: win-2012r2-standard-amd64-nocm

For now I added this to my wrapper recipe:
if node['platform'] == 'windows'
  node.default['filebeat']['conf_dir'] = "#{node['filebeat']['windows']['base_dir']}/filebeat-#{node['filebeat']['version']}-windows"
  node.default['filebeat']['conf_file'] = "#{node['filebeat']['conf_dir']}/filebeat.yml"
  node.default['filebeat']['prospectors_dir'] = "#{node['filebeat']['conf_dir']}/conf.d"
end

**Comment by prerakpshah** [comment]
I experienced the same issue. The above workaround works. On a separate note have you tried to add multiple prospectors using node attributes ?

**Comment by prerakpshah** [comment]
This is now resolved with the latest build.
