### ISSUE TITLE
filebeat is not restarted on upgrade

### ISSUE THREAD

**Issue by sevaorlov** [vkhatri/chef-filebeat#34]
Hi, if upgrade filebeat with filebeat::install_package it is not restarted and change doesn't have an effect.
It happend that I regenerated filebeat configs first and only after it upgraded filebeat. Now I can restart filebeat only manually (as there is no recipe for it) or by changing filebeat config.

**Comment by vkhatri** [comment]
PR Merged, thank you reporting this issue and providing the fix.
