### ISSUE TITLE
Filebeat version attribute is not wrapper friendly

### ISSUE THREAD

**Issue by rhass-r7** [vkhatri/chef-filebeat#4]
The package file name uses a derived attribute, as result the only way to set the version and have it respected is to use a precedence level higher than `default`, along with something like `node.from_file(run_context.resolve_attribute(*parse_attribute_file_spec("filebeat::default")))` 

For this reason, derived attributes are not recommended. 

See https://coderanger.net/derived-attributes/ for additional details.

**Comment by vkhatri** [comment]
@rhass-r7 Thank you raising this issue. I have been thinking to update the cookbook from some time for derived attributes, but have not gotten any time lately.

I have patched the cookbook, could you please give it a try now and let me know if issue still persists?

**Comment by vkhatri** [comment]
Closing.
