### ISSUE TITLE
Chef version 12.9.37 introduced (slightly) incompatible native apt_repository resource

### ISSUE THREAD

**Issue by eherot** [vkhatri/chef-filebeat#41]
The new apt_repository resource adds a default value for "distribution" which of course breaks the filebeat repo config because it doesn't need one. You can work around this by doing:

``` ruby
apt_repository 'your_repo' do
  distribution ''
end
```

See the issue I filed with Chef about it: chef/chef#4828
And the commit that introduced the problem: chef/chef@79548ac

**Comment by vkhatri** [comment]
@eherot thanks for reporting the issue, working on the patch.

**Comment by eherot** [comment]
Love the quick turnaround on this! Thanks @vkhatri!

**Comment by eherot** [comment]
PS. I'm going to call this closed if no one minds.
