### ISSUE TITLE
Is there any setting to enable proxy url for the pulling the packages ?

### ISSUE THREAD

**Issue by prerakpshah** [vkhatri/chef-filebeat#44]

**Comment by vkhatri** [comment]
@prerakpshah You can override attributes `default['filebeat']['yum']['...']` and point it to your local repository.

If you are looking for pulling down a package and configure cookbook to install from a local package, i am afraid that is not supported by the cookbook. It is not an ideal or a recommended way.

**Comment by prerakpshah** [comment]
Thanks!
