### ISSUE TITLE
Version bump for latest changes?

### ISSUE THREAD

**Issue by hartfordfive** [vkhatri/chef-filebeat#47]
@vkhatri I was wondering if you'll have a chance soon to do a version bump to 0.3.2 (or 0.4.0) to reflect the changes this past week and to upload it to the chef Supermarket?  That would be great if that could be done soon, which would allow me to continue using your cookbook instead of forking my own copy.

Thank you!

**Comment by hartfordfive** [comment]
@vkhatri any ideas when you'll have a chance to do a version bump to 0.4.0?  Thanks!

**Comment by vkhatri** [comment]
@hartfordfive Sorry for the delay. I have released version 0.3.2 to supermarket.
