### ISSUE TITLE
Adding Prospectors Using JSON not working.

### ISSUE THREAD

**Issue by prerakpshah** [vkhatri/chef-filebeat#48]
I tried adding prospectors using node attributes in json format. I used the following with chef solo and this doesnot work. Can you assist and point me out what could be the problem here
`{
   "filebeat": {
      "prospectors": {
        "system_logs": {
          "filebeat": {
            "prospectors": [
              {
                "paths": [
                  "/var/log/messages",
                  "/var/log/syslog"
                ],
                "type": "log",
                "fields": {
                  "type": "system_logs"
                }
              }
            ]
          }
        },
        "secure_logs": {
          "filebeat": {
            "prospectors": [
              {
                "paths": [
                  "/var/log/secure",
                  "/var/log/auth.log"
                ],
                "type": "log",
                "fields": {
                  "type": "secure_logs"
                }
              }
            ]
          }
        },
        "apache_logs": {
          "filebeat": {
            "prospectors": [
              {
                "paths": [
                  "/var/log/apache/*.log"
                ],
                "type": "log",
                "ignore_older": "24h",
                "scan_frequency": "15s",
                "harvester_buffer_size": 16384,
                "fields": {
                  "type": "apache_logs"
                }
              }
            ]
          }
        }
      }
    },
  "filebeat": {
    "config": {
      "output": {
        "logstash": {
          "enabled": true,
          "hosts": [
            "127.0.0.1:5044"
          ]
        }
      }
    }
  },
  "run_list": [
    "recipe[filebeat::default]"
  ]
}`

NOTE: I used the above config both with and without the "default_attribute" wrapper and it doesnot work. Whereas, the logstash config passed in works.

**Comment by prerakpshah** [comment]
Folks,
I will really appreciate a quick response on this. I am stuck on it.

**Comment by vkhatri** [comment]
@prerakpshah Sorry for the delay, let me take a look.

**Comment by prerakpshah** [comment]
@vkhatri  Any updates from your end ?

**Comment by vkhatri** [comment]
@prerakpshah Missed it due to missing formatting. You are declaring filebeat attribute twice due to which only output configuration gets added.

```
    "filebeat": {
      "prospectors": {
        "system_logs": {
          "filebeat": {
            "prospectors": [
            {
              "paths": [
                "/var/log/messages",
              "/var/log/syslog"
                ],
              "type": "log",
              "fields": {
                "type": "system_logs"
              }
            }
            ]
          }
        },
        "secure_logs": {
          "filebeat": {
            "prospectors": [
            {
              "paths": [
                "/var/log/secure",
              "/var/log/auth.log"
                ],
              "type": "log",
              "fields": {
                "type": "secure_logs"
              }
            }
            ]
          }
        },
        "apache_logs": {
          "filebeat": {
            "prospectors": [
            {
              "paths": [
                "/var/log/apache/*.log"
                ],
              "type": "log",
              "ignore_older": "24h",
              "scan_frequency": "15s",
              "harvester_buffer_size": 16384,
              "fields": {
                "type": "apache_logs"
              }
            }
            ]
          }
        }
      }
    },
    "filebeat": { # Here
      "config": {
        "output": {
          "logstash": {
            "enabled": true,
            "hosts": [
              "127.0.0.1:5044"
              ]
          }
        }
      }
```

Try below configuration, it should work.

```
    "filebeat": {
      "prospectors": {
        "system_logs": {
          "filebeat": {
            "prospectors": [
            {
              "paths": [
                "/var/log/messages",
              "/var/log/syslog"
                ],
              "type": "log",
              "fields": {
                "type": "system_logs"
              }
            }
            ]
          }
        },
        "secure_logs": {
          "filebeat": {
            "prospectors": [
            {
              "paths": [
                "/var/log/secure",
              "/var/log/auth.log"
                ],
              "type": "log",
              "fields": {
                "type": "secure_logs"
              }
            }
            ]
          }
        },
        "apache_logs": {
          "filebeat": {
            "prospectors": [
            {
              "paths": [
                "/var/log/apache/*.log"
                ],
              "type": "log",
              "ignore_older": "24h",
              "scan_frequency": "15s",
              "harvester_buffer_size": 16384,
              "fields": {
                "type": "apache_logs"
              }
            }
            ]
          }
        }
      },
      "config": {
        "output": {
          "logstash": {
            "enabled": true,
            "hosts": [
              "127.0.0.1:5044"
              ]
          }
        }
      }
    }
```
