### ISSUE TITLE
'enabled' attributes are not properly respected by config.rb

### ISSUE THREAD

**Issue by rhass-r7** [vkhatri/chef-filebeat#5]
The attributes `default['filebeat']['config']['output']['elasticsearch']['enabled']` and `default['filebeat']['config']['output']['logstash']['enabled']` result in sections which are rendered to the config file. In the case of elasticsearch, it attempts to load the plugin and if no hosts are defined fails to start.

The expected behavior is not to render any of the output sections in which the enabled value is set to `false`.

**Comment by vkhatri** [comment]
@rhass-r7 I think it make sense to set `default['filebeat']['config']['output'] = {}` altogether and leave the configuration up to the user.

This way, attribute `default['filebeat']['enable_localhost_output']` can de deprecated.

**Comment by rhass-r7** [comment]
This sounds reasonable to me.

**Comment by vkhatri** [comment]
Removed default `output` configuration attributes and `default['filebeat']['enable_localhost_output']` attribute.
