### ISSUE TITLE
LWRP filebeat_prospector Problem with backslash in regex by using multiline

### ISSUE THREAD

**Issue by ghost** [vkhatri/chef-filebeat#50]
I want to use the following regex within LWRP filebeat_prospector
['multiline']['pattern'] = '^\d{4}\/\d+\/\d+ \d+:\d+:\d+ ['
['multiline']['negate'] = true
['multiline']['match'] = 'after'

But I get on the server:
multiline: !ruby/hash:Chef::Node::ImmutableMash
    pattern: "^\d{4}\/\d+\/\d+ \d+\:\d+:\d+ \["
    negate: true
    match: after

and the error
syslog:May 10 12:30:33 ip-10-18-4-20 /usr/bin/filebeat[28838]: log.go:135: Stop Harvesting. Unexpected encoding line reader error: error parsing regexp: invalid escape sequence: `\d`

**Comment by ghost** [comment]
sorry, I did not insert the output as code in the first comment

```
 multiline: !ruby/hash:Chef::Node::ImmutableMash
      pattern: "^\\d{4}\\/\\d+\\/\\d+ \\d+\\:\\d+:\\d+ \\["
      negate: true
      match: after
```

**Comment by vkhatri** [comment]
@DHampe Could you please share the Chef Server, Chef Client and OS version details?

Anyhow, will update the cookbook for the fix. I know we have had the similar issue with other cookbook too in the past.

**Comment by runningman84** [comment]
The !ruby/hash:Chef::Node::ImmutableMash was our fault... (we defined it in the attributes and a cast to _hash helped here)

But there is another problem, if you look at this sample code:

```
value['paths'] = ['/var/log/nginx/*error.log']
value['type'] = 'nginx-error'
value['multiline']['pattern'] = "^\d{4}\/\d+\/\d+ \d+\:\d+:\d+ \["
value['multiline']['negate'] = true
value['multiline']['match'] = 'after'

  filebeat_prospector key do
    paths value['paths'].to_a
    fields metafields.merge('type' => value['type'])
    fields_under_root true
    multiline value['multiline'].to_hash if value.key?("multiline")
    notifies :restart, 'service[filebeat]', :delayed
  end
```

The generated config file looks like this:

```
...
pattern: "^\\d{4}\\/\\d+\\/\\d+ \\d+\\:\\d+:\\d+ \\["
...
```

Your cookbook seems to double quote the pattern which leads to a parse error in filebeat.

**Comment by vkhatri** [comment]
@runningman84 

Thanks for confirming `ImmutableMash` issue.

The double quotes are added by Ruby. Using `Regexp` is one of the solution to get a regexp into a yaml file, but that does not seems to be agreeing with go lang yaml parser.

``` ruby
new_resource.multiline['pattern'] = Regexp.new(new_resource.multiline['pattern']) 
```

Generated by Regexp :

``` ruby
      pattern: !ruby/regexp /^\d{4}\/\d+\/\d+ \d+\:\d+:\d+ \[/
```

Actual requirement:

``` ruby
      pattern: "/^\d{4}\/\d+\/\d+ \d+\:\d+:\d+ \[/"
```

**Comment by runningman84** [comment]
My workaround is to use a simple regex where I use [0-9] instead of \d

**Comment by vkhatri** [comment]
Closing, thanks @runningman84

**Comment by drenalin23** [comment]
If anyone else runs across this closed issue they might find help at -
https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html
It helped me work around the issue.
