### ISSUE TITLE
enabled option for outputs was deprecated before Filebeat 1.0 release

### ISSUE THREAD

**Issue by drenalin23** [vkhatri/chef-filebeat#55]
Based on - https://github.com/elastic/filebeat/issues/317

I realized you may want to code in for backwards compatibility - but we should get removed from the README/docs.  If it isn't in a branch already I am happy to fork and submit a PR to cleanup any docs references - and remove altogether if you're ok with that too.

**Comment by drenalin23** [comment]
Maybe it will come back -
https://github.com/elastic/beats/issues/1589

**Comment by vkhatri** [comment]
@drenalin23 SGTM
