### ISSUE TITLE
yum package unexpectedly updating to filebeat v1.3.0

### ISSUE THREAD

**Issue by seaniscold** [vkhatri/chef-filebeat#65]
when i leave the version of the cookbook unpinned, do not alter any attributes for the version it installs v1.3.0 of the yum package and subsequent chef runs fail due to a candidate version mismatch. workarounds included pinning the cookbook version or pinning the filbeat version on our own end.

**Comment by vkhatri** [comment]
@seaniscold Working on it.

**Comment by vkhatri** [comment]
Fixed in release v0.3.9
