### ISSUE TITLE
config_dir attribute not getting set

### ISSUE THREAD

**Issue by drenalin23** [vkhatri/chef-filebeat#68]
Further information is cookbook version 0.3.7, Chef 11.8.2.
Since the latest cookbook was pulled in, the config_dir attribute is not getting set properly and now /etc/filebeat/filebeat.yml ends up with a blank field for config directory.
Will post more if I can figure out further why this doesn't get set properly after the move to using attributes.rb.

**Comment by vkhatri** [comment]
@drenalin23 I think i know whats causing this, i moved evaluated attributes from `attributes/default.rb` to `recipes/attributes.rb` but missed `attributes/config.rb`. Will test it and have new cookbook publish shortly.

Thank you for reporting the issue. Will work on specs too.

**Comment by vkhatri** [comment]
@drenalin23 Released v.0.3.8.
