### ISSUE TITLE
Cookbook does not support 32 bit platforms

### ISSUE THREAD

**Issue by rhass-r7** [vkhatri/chef-filebeat#7]
The default behavior for the download URL is to assume 64 bit systems. This means that one needs to either define `node['filebeat']['package_url']` for 32 bit systems exclude it from the run list on those systems.

https://github.com/vkhatri/chef-filebeat/blob/master/recipes/install.rb#L22-L23

The expected behavior is for the cookbook to properly identify the system architecture and download the correct package.

**Comment by vkhatri** [comment]
@rhass-r7 Added 32bit platforms support, could you please give it a try?

**Comment by vkhatri** [comment]
Closing.
