### ISSUE TITLE
Error executing action `restart` on resource 'service[filebeat]'

### ISSUE THREAD

**Issue by SaravananPerumal23** [vkhatri/chef-filebeat#71]
Hi am facing issue when i use runit to start filebeat. After setting the node "default['filebeat']['service']['init_style'] = 'runit'", i get the error when use this cookbook at first

       Error executing action `restart` on resource 'service[filebeat]'
       ================================================================================

       Mixlib::ShellOut::ShellCommandFailed
       ------------------------------------
       Expected process to exit with [0], but received '1'
       ---- Begin output of /sbin/sv restart /etc/service/filebeat ----
       STDOUT: timeout: down: /etc/service/filebeat: 1s, normally up, want up
       STDERR: 
       ---- End output of /sbin/sv restart /etc/service/filebeat ----
       Ran /sbin/sv restart /etc/service/filebeat returned 1
But when i do the Kitchen converge the next time, it works fine.. Need some troubleshooting steps

**Comment by vkhatri** [comment]
@SaravananPerumal23 could you please try v0.4.4?

**Comment by SaravananPerumal23** [comment]
@vkhatri when you run the Filebeat as runit you are not setting the filebeat.yml file in its default location of /etc/service/filebeat/filebeat.yml, so because of this the kitchen converge fails when i use your cookbook. But if i copy this file to this default location manually then it works.

**Comment by vkhatri** [comment]
@SaravananPerumal23 did you try the latest version of the cookbook?

I am able to `kitchen converge` without any issue.

```shell
$ kitchen converge runit-centos-68
....
         * runit_service[filebeat] action nothing (skipped due to action :nothing)
       Recipe: <Dynamically Defined Resource>
         * service[filebeat] action restart
           - restart service service[filebeat]
         * service[filebeat] action start (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 45/108 resources updated in 07 minutes 52 seconds
       Finished converging <runit-centos-68> (8m2.24s).
-----> Kitchen is finished. (8m47.99s)

$ kitchen login runit-centos-68
[vagrant@runit-centos-68 ~]$ sudo -i
[root@runit-centos-68 ~]# ps aux | grep filebeat
root      3338  0.0  0.0   3940   404 ?        Ss   05:29   0:00 runsv filebeat
root      3361  0.0  0.0   4084   444 ?        S    05:29   0:00 svlogd -tt /var/log/filebeat
root      3371  0.1  3.6  26392 18256 ?        Sl   05:29   0:00 /usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat
root      3412  0.0  0.1 103312   876 pts/0    S+   05:30   0:00 grep filebeat
[root@runit-centos-68 ~]#
```

I know runit is not executing `filebeat-god`, but it works.

**Comment by SaravananPerumal23** [comment]
@vkhatri i have made use of the latest version.

I found that the issue is with runit version > 3.0.0. By default i didn't want the filebeat service to be started unless i provide my application specific filebeat.yml from my own cookbook. So i set the attribute 'default['filebeat']['disable_service'] = true' so the service is disabled when the filebeat package is installed. After that my application cookbook sets the config file and then restarts the filebeat service which was working fine with runit=3.0.0.

I initially thought that the issue is with Filebeat cookbook, but i traced that with runit version 3.0.3 they try to restart the runit services whenever the run file of a service changes which triggers starting the filebeat service. By this time, we will have an empty prospectors and output and because of which the converge fails. But if i set the config relating to Prospectors and Output to an attribute file then everything works fine. In my case, i wanted to make use of filebeat.erb file to set the configuration.

So your cookbook version of 0.4.4 works fine with runit. Thanks for your time in validating!!
