### ISSUE TITLE
Windows Install fails due to wrong path

### ISSUE THREAD

**Issue by slimracing** [vkhatri/chef-filebeat#78]
The `install_windows` recipe assumes the unzipped directory will be `node['filebeat']['windows']['base_dir'] + "/filebeat-#{node['filebeat']['version']}-windows"` but when the package is unzipped the actual directory is `node['filebeat']['windows']['base_dir'] + "/filebeat-#{node['filebeat']['version']}-windows-#{filebeat_arch}"`. The result is the configuration files are put in the wrong directory and the `powershell_script 'install filebeat as service'` in the `config` recipe fails due to not finding the install script.

This seems to be a 5.0+ only issue.

**Comment by vkhatri** [comment]
@slimracing could you please give a try to `master` branch? fixed the 5.x version windows directories issue.

**Comment by slimracing** [comment]
Verified the latest version in `master` branch works, thank you.

**Comment by slimracing** [comment]
Verified in 0.4.7 from Supermarket. Closing.
