### ISSUE TITLE
ERROR: apt_package[filebeat] (filebeat::install_package line 57) had an error: Chef::Exceptions::Package: No candidate version available for filebeat

### ISSUE THREAD

**Issue by ralphie02** [vkhatri/chef-filebeat#84]
I keep on getting error "No candidate version available for filebeat." when installing the package. Is anyone else getting this?? I am using debian 7.10 if that helps....

**Comment by dipson** [comment]
Yes I received this too, it appears as though the only version available in the apt repository is version 5.1.2, where the version requested in the chef recipe defaults to 5.1.1.

As a temporary fix, you can set the following attribute and this chef script should work again:

`default['filebeat']['version'] = '5.1.2'`

**Comment by ralphie02** [comment]
tried that initially but i had other configuration that I had removed since then. I'll try this again!!

**Comment by ralphie02** [comment]
Still doesnt work after trying it again with
`include_recipe 'filebeat::default'`
`default['filebeat']['version'] = '5.1.2'`

**Comment by vkhatri** [comment]
@ralphie02  I am able to install `v5.1.2` successfully. Published cookbook version v0.4.6.

**Comment by ralphie02** [comment]
I'll try the newer version as soon as I get the chance. Cheers

**Comment by vkhatri** [comment]
Closing, please check #91 if face this issue in the future.
