### ISSUE TITLE
Support the 'tags' option

### ISSUE THREAD

**Issue by tmichaud314** [vkhatri/chef-filebeat#87]
A list of tags that the Beat includes in the tags field of each published event. Tags make it easy to select specific events in Kibana or apply conditional filtering in Logstash. These tags will be appended to the list of tags specified in the general configuration.

Example:
```
filebeat.prospectors:
- paths: ["/var/log/app/*.json"]
  tags: ["json"]
```

[Reference](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html)

**Comment by kylegoch** [comment]
I see this got merged. Any chance for a version bump? Was just banging my head against the wall in Test Kitchen because I saw the tags in e resource in the code. But then realized i was on Master and not the version.

**Comment by vkhatri** [comment]
@tmichaud314 👍

**Comment by vkhatri** [comment]
@kylegoch Release v0.4.7.
