### ISSUE TITLE
support latest release or keep installed version

### ISSUE THREAD

**Issue by runningman84** [vkhatri/chef-filebeat#91]
Due to a lot of problems in the last weeks it would be great if this cookbook would support installing the latest release instead of a specific version and also allow to just keep the installed version if it is prebaked in an AMI or something like that.

It looks like the filebeat maintainers are not going to hold releases until the problem is fixed:
https://github.com/elastic/beats/issues/3385

**Comment by vkhatri** [comment]
@runningman84 Could you give a try to `master` branch?

Setting `default['filebeat']['ignore_version'] = true` should allow you to use an already installed `filebeat` package or to install latest package.

**Comment by runningman84** [comment]
The master branch works for me...

**Comment by vkhatri** [comment]
@runningman84 Will release `v0.4.8` today.
