### ISSUE TITLE
misleading release tag format

### ISSUE THREAD

**Issue by deepthawtz** [vkhatri/chef-filebeat#97]
Perhaps my fault for expecting release tags to follow semantic versioning (http://semver.org/). I would expect tag updates (e.g., from `0.4.2` to `0.4.3`) to only contain bug fixes and any upgrades to filebeat itself to be either a major or minor tag version change.

I haven't figured out why yet but the new version of filebeat broke log publishing for us and I'd like to avoid that in the future. For now I'm pinning my cookbook version to an exact tag because `~> 0.4.2` rolled out change I wasn't ready for.

**Comment by vkhatri** [comment]
@deepthawtz I agree that cookbook does not follow semantic versioning. But, can be followed for future release.

One of the major change was the `filebeat` version upgrade to `5.x`. But, it should not have any impact on existing infra if filebeat `version` is pinned to `1.x`.

**Comment by deepthawtz** [comment]
cool, thanks. I just wanted to communicate what I experienced and how it surprised me. Solution is to pin the specific cookbook version dependency
